name: "🐞 Bug 报告"
description: 提交一个 Bug 报告
title: "[Bug]: "
labels:
  [
    "bug",
  ]
assignees:
  [
    abgox,
  ]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 开始之前...
      description: 你是否已经做出努力?
      options:
        - label: 你正在使用 PSCompletions 的最新版本。
          required: true
        - label: 你已经阅读了项目的 README 文件。
          required: true
        - label: 你已经在 [Issues](https://github.com/abgox/PSCompletions/issues) 中搜索了相关问题。
          required: true
        - label: 你已经查看了 https://pscompletions.abgox.com/
  - type: dropdown
    id: powershell-version
    attributes:
      label: 你正在使用什么 Powershell 版本?
      description:
        |
        [PowerShell (pwsh)](https://github.com/PowerShell/PowerShell)
        [Windows PowerShell (Windows 内置版本)](https://learn.microsoft.com/powershell/scripting/what-is-windows-powershell)
      options:
        - PowerShell
        - Windows PowerShell
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: 你正在使用什么系统环境?
      options:
        - Windows
        - Other system
      multiple: true
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: bug 复现步骤
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望结果
  - type: textarea
    id: actually-happening
    attributes:
      label: 实际发生了什么?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 还有其他你想要补充的信息吗？
