name: "🐞 Bug report"
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before Start
      description: Have you verified the following?
      options:
        - label: You are using the latest version of PSCompletions.
          required: true
        - label: You have read this repository's README file.
        - label: You have visit https://pscompletions.pages.dev/
        - label: You have search for related issues in [Issues](https://github.com/abgox/PSCompletions/issues).
  - type: dropdown
    id: powershell-version
    attributes:
      label: What Powershell version are you using?
      description: |
        [PowerShell (pwsh)](https://github.com/PowerShell/PowerShell)
        [Windows PowerShell (Windows builtin version)](https://learn.microsoft.com/powershell/scripting/what-is-windows-powershell)
      options:
        - PowerShell
        - Windows PowerShell
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: What system are you using?
      options:
        - Windows
        - Other system
      multiple: true
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
