name: "🐞 Bug 报告"
description: 提交一个 Bug 报告
title: "[Bug]: "
labels: ["bug", "module"]
assignees: [abgox]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 开始之前...
      description: 你是否已经做出努力?
      options:
        - label: 你已经阅读了项目的 README 文件。
          required: true
        - label: 你已经在 [Issues](https://github.com/abgox/PSCompletions/issues) 中搜索了相关问题。
          required: true
        - label: 如果问题和补全菜单的行为相关，请先检查 `psc menu config` 下的相关配置。
          required: true
        - label: 你已经查看了 https://pscompletions.abgox.com/docs/
  - type: input
    id: version
    attributes:
      label: 当前使用的 PSCompletions 版本
      description: 运行 `psc` 查看当前版本
      placeholder: v6.6.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Powershell 版本
      render: console
      placeholder: |
        PS> $PSVersionTable

        Name                           Value
        ----                           -----
        PSVersion                      7.5.0
        PSEdition                      Core
        GitCommitId                    7.5.0
        OS                             Microsoft Windows 10.0.26100
        Platform                       Win32NT
        PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
        PSRemotingProtocolVersion      2.3
        SerializationVersion           1.1.0.1
        WSManStackVersion              3.0
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: bug 复现步骤
      placeholder: |
        如何复现这个 bug?
        描述尽量简单易懂。
        如果可以，请提供截图、动图、录屏等来帮助理解这个问题发生的全过程。
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望结果
      placeholder: |
        你认为它应该是什么样的?
  - type: textarea
    id: actually-happening
    attributes:
      label: 实际发生了什么?
      placeholder: |
        实际发生了什么?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 还有其他你想要补充的信息吗？
