name: ✨ Add Completion Request
description: Request to add a new completion
title: "[Add]: "
labels: ["completion"]
# assignees: [abgox]
body:
  - type: input
    id: completion
    attributes:
      label: What completion need to add? (e.g. cli commands)
      placeholder: git
    validations:
      required: true
  - type: textarea
    id: documentation
    attributes:
      label: Command source for this completion
      description: |
        - What command does this completion come from?
        - Please provide its official documentation link or description.
      placeholder: Enter the command source link or description here.
    validations:
      required: true
  - type: textarea
    id: usage
    attributes:
      label: Please provide a link, method, or description where you can view the command usage.
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
