name: ✨ Update Completion Request
description: Request to update a new completion
title: "[Update]: "
labels: ["completion"]
# assignees: [abgox]
body:
  - type: input
    id: completion
    attributes:
      label: What completion need to update?
      placeholder: git
    validations:
      required: true
  - type: textarea
    id: documentation
    attributes:
      label: What content needs to update in it?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Any additional comments?
