name: ✨ 补全添加请求
description: 请求添加新补全
title: "[Add Completion]: "
labels: ["completion"]
assignees: [abgox]
body:
  - type: input
    id: completion
    attributes:
      label: 什么补全需要添加? (如：cli 命令等)
      description: |
        - 如果补全在 [argc-completions](https://github.com/sigoden/argc-completions) 中存在，[可以与 argc-completions 结合使用](https://pscompletions.abgox.com/tips/pscompletions-and-argc-completions)
        - 如果存在其他模块和 cli 提供补全，也可以使用它们
      placeholder: git
    validations:
      required: true
  - type: textarea
    id: documentation
    attributes:
      label: 此补全的命令来源
      description: |
        - 此补全来源于什么命令？
        - 请提供命令的官网文档链接，或描述。
      placeholder: 例如，输入命令的官网文档链接
    validations:
      required: true
  - type: textarea
    id: usage
    attributes:
      label: 请提供可以查看命令用法的地址、方法或描述。
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 还有其他你想要补充的信息吗？
