name: ✨ 补全更新请求
description: 请求更新现有补全
title: "[Update Completion Request]: "
labels:
  [
    "feature",
    "Update Completion",
  ]
assignees:
  [
    abgox,
  ]
body:
  - type: input
    id: completion
    attributes:
      label: 什么补全需要更新?
      placeholder: git
    validations:
      required: true
  - type: textarea
    id: documentation
    attributes:
      label: 其中什么内容需要更新
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 还有其他你想要补充的信息吗？
