name: 💡Feature Request
description: Request a new feature or enhancement
title: "[Request]: "
labels: ["feature"]
assignees: [abgox]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before Start
      options:
        - label: You are using the latest version of PSCompletions.
          required: true
        - label: You have read this repository's README file.
          required: true
        - label: You have search for related issues in [Issues](https://github.com/abgox/PSCompletions/issues).
          required: true
        - label: If the feature request is related to menu, please ensure that you have checked `psc menu config`.
          required: true
        - label: You have visit https://pscompletions.abgox.com/
  - type: textarea
    id: description
    attributes:
      label: Describe the request
      description: |
        - Please describe your feature request or enhancement in detail.
        - What deficiency does it address in PSCompletions?
        - What use cases support your request?
    validations:
      required: true
  - type: dropdown
    id: powershell-version
    attributes:
      label: What Powershell version are you using?
      description: |
        - [PowerShell (pwsh)](https://learn.microsoft.com/powershell/scripting/overview)
        - [Windows PowerShell 5.1 (Windows builtin version)](https://learn.microsoft.com/powershell/scripting/what-is-windows-powershell)
      options:
        - PowerShell
        - Windows PowerShell
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: What system are you using?
      options:
        - Windows
        - Other system
      multiple: true
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
