name: 💡Feature Request
description: Request a new feature or enhancement
title: "[Request]: "
labels: ["module"]
assignees: [abgox]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before Start
      options:
        - label: You have read this repository's README file.
          required: true
        - label: You have search for related issues in [Issues](https://github.com/abgox/PSCompletions/issues).
          required: true
        - label: If the feature request is related to menu, please ensure that you have checked `psc menu config`.
          required: true
        - label: You have visit https://pscompletions.abgox.com/
  - type: textarea
    id: description
    attributes:
      label: Describe the request
      description: |
        - Please describe your feature request or enhancement in detail.
        - What deficiency does it address in PSCompletions?
        - What use cases support your request?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Current version of PSCompletions
      description: Run `psc` to get the current version
      placeholder: v6.2.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: PowerShell Version
      render: console
      placeholder: |
        PS> $PSVersionTable

        Name                           Value
        ----                           -----
        PSVersion                      7.5.0
        PSEdition                      Core
        GitCommitId                    7.5.0
        OS                             Microsoft Windows 10.0.26100
        Platform                       Win32NT
        PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
        PSRemotingProtocolVersion      2.3
        SerializationVersion           1.1.0.1
        WSManStackVersion              3.0
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
