name: 💡 功能请求
description: 请求一个新功能或功能增强
title: "[Request]: "
labels: ["feature"]
assignees: [abgox]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 开始之前...
      options:
        - label: 你正在使用 PSCompletions 的最新版本。
          required: true
        - label: 你已经阅读了项目的 README 文件。
          required: true
        - label: 你已经在 [Issues](https://github.com/abgox/PSCompletions/issues) 中搜索了相关问题。
          required: true
        - label: 如果功能请求和补全菜单相关，请先检查 `psc menu config` 下的相关配置。
          required: true
        - label: 你已经查看了 https://pscompletions.abgox.com/
  - type: textarea
    id: description
    attributes:
      label: 描述这个功能请求
      description: |
        - 目前 PSCompletions 存在哪些不足？
        - 详细描述你需要的功能需求或想法。
        - 你认为有哪些可行的实现方案作为参考？
    validations:
      required: true
  - type: dropdown
    id: powershell-version
    attributes:
      label: 你正在使用什么 Powershell 版本?
      description: |
        - [PowerShell (pwsh)](https://learn.microsoft.com/powershell/scripting/overview)
        - [Windows PowerShell 5.1 (Windows 内置版本)](https://learn.microsoft.com/powershell/scripting/what-is-windows-powershell)
      options:
        - PowerShell
        - Windows PowerShell
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: 你正在使用什么系统环境?
      options:
        - Windows
        - Other system
      multiple: true
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 还有其他你想要补充的信息吗？
