name: 💡 功能请求
description: 请求一个新功能或功能增强
title: "[Request]: "
labels:
  [
    "feature",
  ]
assignees:
  [
    abgox,
  ]
body:
  - type: textarea
    id: description
    attributes:
      label: 描述这个功能请求
      description:
        |
        请详细描述您的功能要求或增强。
        它解决了 PSCompletions 中的哪些不足?
        哪些用例支持您的请求?
    validations:
      required: true
  - type: dropdown
    id: powershell-version
    attributes:
      label: 你正在使用什么 Powershell 版本?
      description:
        |
        [PowerShell (pwsh)](https://github.com/PowerShell/PowerShell)
        [Windows PowerShell (Windows 内置版本)](https://learn.microsoft.com/powershell/scripting/what-is-windows-powershell)
      options:
        - PowerShell
        - Windows PowerShell
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: 你正在使用什么系统环境?
      options:
        - Windows
        - Other system
      multiple: true
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 还有其他你想要补充的信息吗？
