#
# Module manifest for module 'PSCompletions'
#
# Generated by: abgox
#
# Generated on: 2023/8/15
#

@{
    RootModule           = 'PSCompletions.psm1'

    ModuleVersion        = '6.2.2'

    GUID                 = '00929632-527d-4dab-a5b3-21197faccd05'

    Author               = 'abgox'

    Copyright            = 'Copyright (c) 2023-present abgox. All Rights Reserved.'

    PowerShellVersion    = '5.1'

    CompatiblePSEditions = @('Core', 'Desktop')

    Description          = 'A completion manager for a better and simpler tab-completion experience in PowerShell.
 It provides an enhanced scrollable completion menu with sorting and filtering.
  - Website: https://pscompletions.abgox.com
  - Github:  https://github.com/abgox/PSCompletions
  - Gitee:   https://gitee.com/abgox/PSCompletions'

    ScriptsToProcess     = 'core.ps1'

    PrivateData          = @{

        PSData = @{

            Tags         = @('psc', 'Tab', 'Completion', 'Prompt', 'TabExpansion', 'Completions', 'Dynamic', 'Multi-Language', 'Base-in-json', 'Completion-Manager', 'TabExpansion2', 'Menu', 'TUI' , 'GUI' , 'PowerShell', 'pwsh', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows', 'Linux', 'MacOS')

            LicenseUri   = 'https://github.com/abgox/PSCompletions/blob/main/LICENSE'

            ProjectUri   = 'https://pscompletions.abgox.com'

            IconUri      = 'https://pscompletions.abgox.com/logo.svg'

            ReleaseNotes = 'https://github.com/abgox/PSCompletions/blob/main/module/CHANGELOG.md'

        }

    }

    HelpInfoUri          = 'https://pscompletions.abgox.com'
}

